### ISSUE TITLE
I got NetworkError: 403 Forbidden

### ISSUE THREAD

**Issue by kidesigner** [nukulb/s3-angular-file-upload#13]
I got NetworkError: 403 Forbidden, i see "SignatureDoesNotMatch" please help me!

**Comment by nukulb** [comment]
@kidesigner Resizing the image is obviously a more interesting problem. 

2 ways I can suggest:

1) Upload the file s3, download on your server and then resize and upload back to s3. Here is an interesting project I am using right now - https://github.com/EyalAr/lwip
There are also a lot of paid services for such operations.

2) You can do it all in browser but I am uncertain how well this works since I don't use this method. http://stackoverflow.com/questions/19262141/resize-image-with-javascript-canvas-smoothly
