### ISSUE TITLE
How to remove a file from s3 bucket?

### ISSUE THREAD

**Issue by piotrkulpinski** [nukulb/s3-angular-file-upload#16]
Hi Nukulb,
I really love your work - it helped me a lot with setting up s3 upload in angular app.
I was wondering if you know any way to remove a file from s3 bucket using ng-file-upload module?

Thanks.

**Comment by nukulb** [comment]
@piotrkulpinski glad you like the work.

ng-file-upload is simply an upload framework so you cannot use it to delete a file from s3.

Although there are a couple of different ways this can easily be accomplished.

1) If you are using a supported framework you can simply use AWS-SDK to delete the file from your server. This would be easiest way. So your angular app makes a rest call to your server, server calls the AWS SDK that does the work

In nodejs your code will look like this
```
npm install aws-sdk
```
```
var  s3 = new AWS.S3();
var deleteFileFromS3 = exports.deleteFileFromS3= function (key, callback) {

    s3.deleteObject({
        Bucket: awsConfig.bucket,
        Key: key
    }, function (err) {
        if (err) {
            logger.info('Error occurred during delete from S3', err);
            return callback(err);
        } else {
            return callback(null);
        }
    });
};
```

Then your rest call can simply call the method above.

2) If you are adventurous enough I am sure this is possible straight from the browser as well although there does not seem to be any advantage of that.
The true advantage of directly uploading a file to s3 is that you don't hit your server at all and hence its easier to manage than to upload to your server and then upload to s3 from there.
In this case you would generate a signature, similar to how its done in the example in this repo.
https://github.com/nukulb/s3-angular-file-upload/blob/master/lib/controllers/aws.js#L15

After you generate the signature, you should be able to call
$http.del on the file plus some parameters.
This might be not be the simplest thing to get it working since the documentation is sparse and I suggest avoiding it.

Thanks for reaching out.
